# Generated by Django 5.1.2 on 2024-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='descripiton',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
